### PR TITLE
Update GitVersion 3.6.3

### PR DESCRIPTION
**Pull request by danielmarbach**
Connects to https://github.com/Particular/V6Launch/issues/3

@Particular/servicecontrol-maintainers please review and merge

### CODE REVIEW

**Comment by johnsimons** [comment]
I would rather not have to maintain the release date manually, do we really need to be running v3 ?
@mikeminutillo thoughts ?

**Comment by danielmarbach** [comment]
do we need the release date attribute in the plugins? I don't think we do

**Comment by johnsimons** [comment]
good point @danielmarbach, happy

**Comment by andreasohlund** [comment]
Yea, those dates are only used by core, SI and SC

**Pull request merged**
